# Dependabot configuration for GAN Cyber Range Simulator
# Advanced dependency management with security-focused grouping
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "security-team"
    assignees:
      - "maintainers"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
      - "automated"
    allow:
      - dependency-type: "all"
    # Group related updates together for easier review
    groups:
      security-updates:
        patterns:
          - "bandit*"
          - "safety*"
          - "semgrep*"
          - "cryptography*"
        update-types:
          - "minor"
          - "patch"
      ai-ml-frameworks:
        patterns:
          - "openai*"
          - "anthropic*"
          - "langchain*"
          - "torch*"
          - "stable-baselines3*"
          - "numpy*"
          - "pandas*"
        update-types:
          - "minor"
          - "patch"
      testing-frameworks:
        patterns:
          - "pytest*"
          - "coverage*"
        update-types:
          - "minor"
          - "patch"
      development-tools:
        patterns:
          - "black*"
          - "ruff*"
          - "mypy*"
          - "pre-commit*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      # Ignore major version updates for AI frameworks (breaking changes)
      - dependency-name: "openai"
        update-types: ["version-update:semver-major"]
      - dependency-name: "anthropic"
        update-types: ["version-update:semver-major"]
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "langchain"
        update-types: ["version-update:semver-major"]
      # Ignore beta/pre-release versions
      - dependency-name: "*"
        update-types: ["version-update:semver-prerelease"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainers"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "docker"
      - "dependencies"
      - "automated"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"  
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainers"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci/cd"
      - "automated"
    allow:
      - dependency-type: "direct"
    ignore:
      # Pin specific actions to stable versions
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]