name: 🚀 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - "Core Agent System"
        - "Cyber Range Environment"
        - "Security Framework"
        - "API/Interface"
        - "Documentation"
        - "CI/CD Pipeline"
        - "Containerization"
        - "Monitoring/Metrics"
        - "User Interface"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would improve workflow"
        - "High - Significant impact on usability"
        - "Critical - Blocking current work"
    validations:
      required: true

  - type: checkboxes
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature is this? (Check all that apply)
      options:
        - label: New functionality
        - label: Performance improvement
        - label: Security enhancement
        - label: User experience improvement
        - label: Developer experience improvement
        - label: Integration with external tool
        - label: Configuration option
        - label: API enhancement

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, add mockups, examples, or references to help explain your feature request.
      placeholder: Paste images, links, or examples here...

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - "Low - Simple configuration or minor change"
        - "Medium - New component or significant change"
        - "High - Major architectural change"
        - "Unknown"

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Considerations
      description: Please check any relevant considerations
      options:
        - label: This may require breaking changes
        - label: This may affect security
        - label: This may affect performance
        - label: This may require new dependencies
        - label: This may require database changes
        - label: This may affect existing APIs

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to implement this feature
        - label: I am willing to help test this feature
        - label: I am willing to help with documentation
        - label: I am willing to provide feedback during development

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request here.
      placeholder: Any additional information that might be helpful...