name: 🔒 Security Vulnerability
description: Report a security vulnerability (private disclosure)
title: "[Security]: "
labels: ["security", "critical"]
assignees: ["danieleschmidt"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT SECURITY NOTICE** ⚠️
        
        If you believe you have found a security vulnerability, please DO NOT create a public issue.
        Instead, please email us directly at: **security@gan-cyber-range.org**
        
        For immediate security concerns, you can also contact:
        - danieleschmidt (GitHub: @danieleschmidt)
        
        We take security vulnerabilities seriously and will respond within 24 hours.

  - type: textarea
    id: vulnerability_type
    attributes:
      label: Vulnerability Type
      description: What type of vulnerability is this?
      placeholder: |
        - [ ] Code injection (SQL, command, etc.)
        - [ ] Cross-site scripting (XSS)
        - [ ] Authentication bypass
        - [ ] Authorization issue
        - [ ] Information disclosure
        - [ ] Container security issue
        - [ ] Dependency vulnerability
        - [ ] Cryptographic issue
        - [ ] Other (specify)

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Please provide a detailed description of the vulnerability
      placeholder: Describe the security issue in detail...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Assessment
      description: What is the potential impact of this vulnerability?
      placeholder: |
        - Data that could be accessed/modified
        - Systems that could be compromised
        - Potential for privilege escalation
        - Scope of affected users/systems
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the vulnerability (if safe to include)
      placeholder: |
        1. Step 1
        2. Step 2
        3. See vulnerability
        
        Note: If reproduction steps involve sensitive information, please include this in your private email instead.

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for how to fix this vulnerability?
      placeholder: Suggested fix or mitigation approach...

  - type: dropdown
    id: severity
    attributes:
      label: Severity Assessment
      description: How would you rate the severity of this vulnerability?
      options:
        - "Critical - Immediate threat to system security"
        - "High - Significant security risk"
        - "Medium - Moderate security concern"
        - "Low - Minor security issue"
        - "Unknown"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Affected Environment
      description: Which environments are affected?
      placeholder: |
        - Development environment
        - Staging environment  
        - Production environment
        - Container environment
        - Kubernetes deployment
        - Specific versions affected

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your understanding of responsible disclosure
      options:
        - label: I understand this is a security-sensitive issue
          required: true
        - label: I will not publicly disclose details until a fix is available
          required: true
        - label: I have not shared this vulnerability information with others
          required: true
        - label: I am willing to work with the maintainers to resolve this issue
          required: true

  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you for follow-up? (Optional but recommended)
      placeholder: |
        Email: your-email@example.com
        GitHub: @yourusername
        Preferred contact method: email/GitHub/other

  - type: markdown
    attributes:
      value: |
        ---
        
        **After submitting this issue:**
        1. We will acknowledge receipt within 24 hours
        2. We will provide an initial assessment within 72 hours
        3. We will work with you to understand and reproduce the issue
        4. We will develop and test a fix
        5. We will coordinate disclosure timing with you
        6. We will credit you in our security advisory (if desired)
        
        Thank you for helping keep our project secure! 🙏