apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gan-cyber-range-hpa
  namespace: cyber-range
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gan-cyber-range
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - 
type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70