name: "CI/CD Pipeline"
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
uses: actions/checkout@v4
      - 
name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - 
name: "Install dependencies"
        run: "pip install -r requirements-minimal.txt"
      - 
name: "Run tests"
        run: "python3 test_suite.py"
      - 
name: "Run security scan"
        run: "python3 security_quality_gates.py || true"
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: "github.ref == 'refs/heads/main'"
    permissions:
      contents: read
      packages: write
    steps:
      - 
uses: actions/checkout@v4
      - 
name: "Log in to Container Registry"
        uses: docker/login-action@v3
        with:
          registry: "${{ env.REGISTRY }}"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - 
name: "Extract metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
      - 
name: "Build and push Docker image"
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: production
    steps:
      - 
uses: actions/checkout@v4
      - 
name: "Deploy to Kubernetes"
        run: "
                                echo "Deploying to Kubernetes cluster..."
                                # kubectl apply -f k8s/
                                echo "Deployment completed"
                            "